/////////////////////////////////////
// ARO clusters
/////////////////////////////////////

// ARO clusters and their worker profiles
resources
| where type =~ "microsoft.redhatopenshift/openshiftclusters"
| mv-expand wp = properties.workerProfiles
| extend nodeName = wp.name, nodeSize = wp.vmSize
| project subscriptionId, resourceGroup, name, location, version = properties.clusterProfile.version, nodeName, nodeSize, tags