/////////////////////////////////////
// Virtual Machines
/////////////////////////////////////

// VM redundancy settings (none / AvSet / AvZone)
resources
| where type =~ 'Microsoft.Compute/virtualMachines'
| extend availabilitySet = properties.availabilitySet.id, availabilityZone = zones, vmSize = properties.hardwareProfile.vmSize, PPG = split(properties.proximityPlacementGroup.id, "/")[-1]
| project subscriptionId, resourceGroup, name, location, vmSize, availabilitySet, availabilityZone, PPG

// Proximity placement group settings
| join kind=leftouter (
    resources
    | where type =~ 'Microsoft.Compute/proximityPlacementGroups'
    | project proximityPlacementGroup = name, vmId = id
) on $left.id == $right.vmId
