/////////////////////////////////////
// SQL Server IaaS/PaaS
/////////////////////////////////////

// SQL Server machines and versions
resources
| where type =~ 'microsoft.sqlvirtualmachine/sqlvirtualmachines'
| project subscriptionId, resourceGroup, name, location, image = properties.sqlImageOffer, sku = properties.sqlImageSku, licenseType = properties.sqlServerLicenseType

// Azure SQL databases
resources
| where type =~ 'microsoft.sql/servers/databases'
