/////////////////////////////////////
// Disks
/////////////////////////////////////

// VM name, location, disk name, and disk SKU
resources
| extend lowerId = tolower(id)
| join kind=inner (
    resources
    | where type == "microsoft.compute/disks"
    | extend diskSku = tostring(sku.name)
    | project diskName = name, diskSku, vmId = tolower(managedBy), sizeGb = properties.diskSizeGB
) on $left.lowerId == $right.vmId
| project-away vmId
| project subscriptionId, vmName = name, location, diskName, diskSku, sizeGb, tags

/////////////////////////////////////
// Backup vaults
/////////////////////////////////////

// List backup vaults together with their SKU
resources
| where type == "microsoft.recoveryservices/vaults"
| extend sku = tostring(properties.redundancySettings.standardTierStorageRedundancy)
| project subscriptionId, resourceGroup, location, name, sku

/////////////////////////////////////
// Storage accounts
/////////////////////////////////////

// List storage accounts together with their SKU
resources
| where type == "microsoft.storage/storageaccounts"
| extend sku = tostring(sku.name)
| project subscriptionId, resourceGroup, name, location, kind, sku

/////////////////////////////////////
// NetApp resources
/////////////////////////////////////

// Show NetApp accounts, pools, volumes and their sizes
resources
| where type == "microsoft.netapp/netappaccounts/capacitypools/volumes"
| project subscriptionId, resourceGroup, location, name, account = split(name, "/")[0], pool = split(name, "/")[1], volume = split(name, "/")[2], tier = properties.serviceLevel, sizeTB = properties.usageThreshold/1024/1024/1024, tags
